import React,{useMemo,useState} from 'react'
import {createInvoice,updateInvoice,deleteInvoice,generateInvoiceNumber} from './lib/invoicesApi'
const money=v=>Number(v||0).toLocaleString('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2})+' zł'
const today=()=>new Date().toISOString().slice(0,10)
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
const total=j=>{const q=j?.quantities||{},r=j?.rates||{};return Number(q.mb||0)*Number(r.mb||0)+Number(q.m2||0)*Number(r.m2||0)+Number(q.kg||0)*Number(r.kg||0)}
const items=j=>{if(!j)return[];const q=j.quantities||{},r=j.rates||{};return[['Prace wentylacyjne – mb',q.mb,r.mb,'mb'],['Prace wentylacyjne – m²',q.m2,r.m2,'m²'],['Prace wentylacyjne – kg',q.kg,r.kg,'kg']].filter(x=>Number(x[1]||0)>0&&Number(x[2]||0)>0).map(x=>({name:x[0],quantity:Number(x[1]),netUnit:Number(x[2]),unit:x[3],vatRate:23}))}
const amounts=it=>{const net=(it||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.netUnit||0),0);const vat=(it||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.netUnit||0)*Number(x.vatRate||0)/100,0);return{net,vat,gross:net+vat}}
const input={width:'100%',boxSizing:'border-box',padding:'11px 12px',border:'1px solid #d7e2eb',borderRadius:'11px',background:'#fff',color:'#17243d',fontSize:'14px'}
const label={display:'block',marginBottom:'6px',color:'#64748b',fontSize:'11px',fontWeight:800,textTransform:'uppercase'}
export default function InvoicesPage({invoices=[],jobs=[],clients=[],onAlert,onConfirm}){
 const [edit,setEdit]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[saving,setSaving]=useState(false)
 const cm=useMemo(()=>new Map(clients.map(c=>[String(c.id),c])),[clients]),jm=useMemo(()=>new Map(jobs.map(j=>[String(j.id),j])),[jobs])
 const open=async job=>{const n=await generateInvoiceNumber();const t=job?total(job):0;setEdit({jobId:job?.id||'',clientId:job?.clientId||'',invoiceNumber:n,issueDate:today(),saleDate:today(),dueDate:addDays(today(),14),status:'Do wystawienia',paymentMethod:'Przelew',items:items(job),netAmount:t,vatAmount:t*.23,grossAmount:t*1.23,paidAmount:0,notes:''})}
 const save=async()=>{if(!edit.clientId){onAlert?.('Wybierz klienta.');return}setSaving(true);try{const x=edit.id?await updateInvoice(edit):await createInvoice(edit);setEdit(null);window.dispatchEvent(new CustomEvent('aeroinstal-invoices-changed',{detail:x}));onAlert?.('Faktura została zapisana.')}catch(e){console.error(e);onAlert?.('Nie udało się zapisać faktury.')}finally{setSaving(false)}}
 const remove=async x=>{if(!(await onConfirm?.('Usunąć fakturę '+x.invoiceNumber+'?')))return;await deleteInvoice(x.id);window.dispatchEvent(new CustomEvent('aeroinstal-invoices-changed',{detail:{deletedId:x.id}}))}
 if(edit){const a=amounts(edit.items);return <div className="sub-page"><div className="page-heading"><div><div className="small-label">AEROINSTAL</div><h1>{edit.id?'Edytuj fakturę':'Nowa faktura'}</h1></div></div><div className="detail-card" style={{display:'grid',gap:'12px'}}>
 <div><label style={label}>Numer faktury</label><input style={input} value={edit.invoiceNumber} onChange={e=>setEdit({...edit,invoiceNumber:e.target.value})}/></div>
 <div><label style={label}>Klient</label><select style={input} value={edit.clientId} onChange={e=>setEdit({...edit,clientId:e.target.value})}><option value="">Wybierz klienta</option>{clients.map(c=><option key={c.id} value={c.id}>{c.shortName||c.name}</option>)}</select></div>
 <div><label style={label}>Robota</label><select style={input} value={edit.jobId||''} onChange={e=>{const j=jm.get(e.target.value);const it=items(j);const a=amounts(it);setEdit({...edit,jobId:e.target.value,clientId:j?.clientId||edit.clientId,items:it,...{netAmount:a.net,vatAmount:a.vat,grossAmount:a.gross}})}}><option value="">Bez powiązania</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.name||'Bez nazwy'}{j.location?' • '+j.location:''}</option>)}</select></div>
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9}}><div><label style={label}>Data wystawienia</label><input type="date" style={input} value={edit.issueDate} onChange={e=>setEdit({...edit,issueDate:e.target.value})}/></div><div><label style={label}>Termin płatności</label><input type="date" style={input} value={edit.dueDate||''} onChange={e=>setEdit({...edit,dueDate:e.target.value})}/></div></div>
 <div><label style={label}>Status</label><select style={input} value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{['Do wystawienia','Wystawiona','Częściowo zapłacona','Zapłacona','Przeterminowana','Wysłana do KSeF','Błąd KSeF'].map(s=><option key={s}>{s}</option>)}</select></div>
 <div><div className="small-label">POZYCJE</div>{edit.items.map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1.6fr .7fr .8fr .5fr',gap:6,marginTop:7}}><input style={input} value={x.name} onChange={e=>{const it=[...edit.items];it[i]={...it[i],name:e.target.value};setEdit({...edit,items:it})}}/><input style={input} type="number" value={x.quantity} onChange={e=>{const it=[...edit.items];it[i]={...it[i],quantity:Number(e.target.value)};const a=amounts(it);setEdit({...edit,items:it,netAmount:a.net,vatAmount:a.vat,grossAmount:a.gross})}}/><input style={input} type="number" value={x.netUnit} onChange={e=>{const it=[...edit.items];it[i]={...it[i],netUnit:Number(e.target.value)};const a=amounts(it);setEdit({...edit,items:it,netAmount:a.net,vatAmount:a.vat,grossAmount:a.gross})}}/><input style={input} type="number" value={x.vatRate} onChange={e=>{const it=[...edit.items];it[i]={...it[i],vatRate:Number(e.target.value)};const a=amounts(it);setEdit({...edit,items:it,netAmount:a.net,vatAmount:a.vat,grossAmount:a.gross})}}/></div>)}</div>
 <div style={{padding:12,border:'1px solid #d7e2eb',borderRadius:12,background:'#f8fbfe'}}>Netto: <strong>{money(a.net)}</strong> • VAT: <strong>{money(a.vat)}</strong> • Brutto: <strong>{money(a.gross)}</strong></div>
 <div><label style={label}>Uwagi</label><textarea rows="3" style={{...input,resize:'vertical'}} value={edit.notes||''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></div>
 <div style={{display:'grid',gridTemplateColumns:'.8fr 1.2fr',gap:9}}><button type="button" onClick={()=>setEdit(null)} style={{minHeight:50,border:'1px solid #f0caca',borderRadius:12,background:'#fff7f7',color:'#b45454',fontWeight:800}}>Anuluj</button><button type="button" disabled={saving} onClick={save} style={{minHeight:50,border:0,borderRadius:12,background:'#168fe5',color:'#fff',fontWeight:850}}>{saving?'Zapisywanie…':'💾 Zapisz fakturę'}</button></div>
 </div></div>}
 const list=invoices.filter(x=>{const c=cm.get(String(x.clientId)),j=jm.get(String(x.jobId)),t=[x.invoiceNumber,c?.shortName,c?.name,j?.name,x.status].join(' ').toLowerCase();return(!query||t.includes(query.toLowerCase()))&&(filter==='all'||x.status===filter)})
 return <div className="sub-page"><div className="page-heading"><div><div className="small-label">AEROINSTAL</div><h1>Faktury</h1></div><button type="button" onClick={()=>open()} style={{minHeight:44,padding:'0 14px',border:0,borderRadius:12,background:'#168fe5',color:'#fff',fontWeight:800}}>+ Nowa faktura</button></div>
 <div className="dashboard-grid">{[['Wszystkie',invoices.length],['Do wystawienia',invoices.filter(x=>x.status==='Do wystawienia').length],['Wystawione',invoices.filter(x=>x.status==='Wystawiona').length],['Zapłacone',invoices.filter(x=>x.status==='Zapłacona').length]].map(([l,v])=><div className="dashboard-card" key={l}><div className="dashboard-icon">🧾</div><div><span>{l}</span><strong>{v}</strong></div></div>)}</div>
 <div className="detail-card" style={{display:'grid',gap:9}}><input style={input} placeholder="Szukaj faktury, klienta lub roboty…" value={query} onChange={e=>setQuery(e.target.value)}/><div style={{display:'flex',gap:6,overflowX:'auto'}}>{['all','Do wystawienia','Wystawiona','Częściowo zapłacona','Zapłacona','Przeterminowana','Wysłana do KSeF','Błąd KSeF'].map(x=><button type="button" key={x} onClick={()=>setFilter(x)} style={{whiteSpace:'nowrap',padding:'8px 10px',borderRadius:10,border:'1px solid #d7e2eb',background:filter===x?'#e9f5ff':'#fff',fontWeight:700}}>{x==='all'?'Wszystkie':x}</button>)}</div></div>
 <div style={{display:'grid',gap:9}}>{list.map(x=>{const c=cm.get(String(x.clientId)),j=jm.get(String(x.jobId));return <div key={x.id} className="detail-card" style={{padding:13}}><div style={{display:'flex',justifyContent:'space-between'}}><button type="button" onClick={()=>setEdit({...x})} style={{border:0,background:'transparent',padding:0,fontWeight:850,color:'#12234f',fontSize:15}}>{x.invoiceNumber}</button><strong>{money(x.grossAmount)}</strong></div><div style={{fontSize:12,color:'#64748b',marginTop:4}}>{c?.shortName||c?.name||'Brak klienta'}{j?.name?' • '+j.name:''}</div><div style={{fontSize:11,color:'#64748b',marginTop:6}}>Termin: {x.dueDate?new Date(x.dueDate).toLocaleDateString('pl-PL'):'—'} • {x.status}</div><button type="button" onClick={()=>remove(x)} style={{marginTop:8,border:0,background:'transparent',color:'#b45454',fontWeight:800,fontSize:12}}>Usuń</button></div>})}</div>
 {list.length===0&&<div className="detail-card" style={{textAlign:'center',color:'#718096'}}>Brak faktur.</div>}</div>
}
